'use client';

import 'bootstrap/dist/css/bootstrap.min.css';
<<<<<<< HEAD
import { useState } from 'react';
import { Outfit } from 'next/font/google';
import Navbar from "../src/components/Navbar/Navbar";
import Footer from "../src/components/Footer/Footer";
import Sidebar from "../src/components/Sidebar/Sidebar";
import "./globals.css";
=======
import { Outfit } from 'next/font/google';
>>>>>>> 051d8cc176cc9ea9bc418c03bc8edef02867b1bb

const outfit = Outfit({ 
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

<<<<<<< HEAD
  return (
    <html lang="pt-br" className={outfit.className}>
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0" />
      </head>
      <body>
        <Navbar onMenuClick={() => setIsSidebarOpen(true)} />
        <Sidebar isOpen={isSidebarOpen} onClose={() => setIsSidebarOpen(false)} />
        {children}
        <Footer />
      </body>
=======
const outfit = Outfit({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700','800','900']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
>>>>>>> 051d8cc176cc9ea9bc418c03bc8edef02867b1bb
    </html>
  );
}